language: dart
dist : xenial
install:
  - ./flutter/bin/flutter doctor
script:
  - cd picki
  - ../flutter/bin/flutter $COMMAND
cache:
  directories:
    -  $HOME/.pub-cache
matrix:
  include:
  - name: Test
    env: COMMAND=test
  - name: Analyze
    env: COMMAND=analyze
